[config]
default_to_workspace = false

[env]
CARGO_TERM_COLOR = "always"

[tasks.pre-commit]
run_task = { name = ["test", "clippy", "doc", "check_fmt"], parallel = true }

[tasks.ci_main]
run_task = { name = ["test", "clippy", "doc", "check_fmt"], parallel = true }

[tasks.ci_post]
run_task = { name = ["no_untracked", "no_modified", "release"] }

[tasks.ci]
run_task = { name = ["ci_main", "ci_post"] }

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--", "--deny", "warnings"]

[tasks.doc]
command = "cargo"
args = ["doc"]

[tasks.check_fmt]
command = "cargo"
args = ["fmt", "--check"]

[tasks.lint_commit_msg_from_stdin]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo bin conventional_commits_linter --allow-angular-type-only --from-stdin
'''

[tasks.table_of_contents]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
toc=$(cargo bin md-toc --header "# Table of contents" README.md | grep --invert-match --fixed-strings '1. [Table of contents]')
MARKER='<!-- TOC -->'
cargo bin sd "$MARKER[\S\s]*$MARKER" $"$MARKER$toc\n$MARKER" README.md
'''

[tasks.no_modified]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
if ! git diff --exit-code; then
  echo "modified files detected"
  exit 1
fi
'''

[tasks.no_untracked]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
if [[ `git ls-files --exclude-standard --others` ]]; then
  echo "untracked files detected"
  exit 1
fi
'''

[tasks.release]
condition = { env = { "GITHUB_REF_TYPE" = "branch", "GITHUB_REF_NAME" = "master" } }
script = '''
#!/usr/bin/env bash
set -euxo pipefail
npm install --global \
    semantic-release@19 \
    @semantic-release-cargo/semantic-release-cargo@2 \
    @semantic-release/changelog@6 \
    @semantic-release/git@10 \
    conventional-changelog-conventionalcommits@5

semantic-release
'''
