[config]
default_to_workspace = false

[env]
CARGO_TERM_COLOR = "always"

[tasks.pre-commit]
env = { RUSTFLAGS = "--deny warnings" }
dependencies = ["test", "clippy", "doc", "check_fmt"]

[tasks.build]
command = "cargo"
args = ["build", "--all-targets"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets"]

[tasks.doc]
command = "cargo"
args = ["doc"]

[tasks.check_fmt]
command = "cargo"
args = ["fmt", "--check"]

[tasks.lint_commits]
private = true
install_crate = { crate_name = "conventional_commits_linter", binary = "conventional_commits_linter", test_arg = "--version" }
script = "conventional_commits_linter --allow-angular-type-only $ARGS"

[tasks.commit-msg]
private = false
extend = "lint_commits"
env = { ARGS = "--from-stdin" }

[tasks.lint_pr_commit_msgs]
private = false
extend = "lint_commits"
env = { ARGS = "--from-reference ${GITHUB_BASE_REF}" }
