name: On push to master or pull_request

on:
  push:
    branches: [master]
  pull_request: {}

env:
  RUSTFLAGS: --deny warnings

jobs:
  cargo_install:
    uses: ./.github/workflows/run-a-cargo-make-task.yml
    with:
      task: cargo_install

