name: Run a cargo-make task

on:
  workflow_call:
    inputs:
      task:
        required: true
        type: string

jobs:
  run-a-cargo-make-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml', '~/.cargo/.crates.toml', '~/.cargo/.crates2.json') }}
      - uses: davidB/rust-cargo-make@v1
      - run: "cargo make ${{ inputs.task }}"

